name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.toolchain }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain: [stable]
        command: [test --workspace --all-targets --all-features]
        include:
          - os: ubuntu-latest
            toolchain: 1.71.1
            command: check -p pear -p pear_codegen --lib
          - os: ubuntu-latest
            toolchain: beta
            command: test --workspace --all-features
          - os: ubuntu-latest
            toolchain: nightly
            command: test --workspace --all-features

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Run Cargo
        run: cargo ${{ matrix.command }}
